services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  api-gateway:
    build: 
      context: ./DeliVeggieApp.APIGateway/DeliVeggieApp.APIGateway
    ports:
      - "7002:8080"
    networks:
      - my-network
    environment:
      - API_GATEWAY_PORT=8080
  dotnet-api:
    build: 
      context: ./DeliVeggieApp.WebApi/DeliVeggieApp.WebApi
    depends_on:
      - rabbitmq  
    ports:
      - "8081:8081" 
    networks:
      - my-network
    environment:
      - DOTNET_API_PORT=8081
      - RabbitMq__HostName=rabbitmq
  consoleapp:
    build:
      context: ./VeggieAppConsole/VeggieAppConsole
    depends_on:
      - rabbitmq  
    ports:
      - "8082:80"
    networks:
      - my-network
    environment:
      - RabbitMq__HostName=rabbitmq          
  angular-app:
    build:
      context: ./DeliVeggieFrontEnd/angular-app
    ports:
      - "5000:80"
    networks:
      - my-network  
networks:
  my-network:
    driver: bridge