services:
  api-gateway:
    build: 
      context: ./DeliVeggieApp.APIGateway/DeliVeggieApp.APIGateway
    ports:
      - "7002:8080"
    networks:
      - my-network
    environment:
      - API_GATEWAY_PORT=8080
  dotnet-api:
    build: 
      context: ./DeliVeggieApp.WebApi/DeliVeggieApp.WebApi
    image: veggieapp.webapi
    ports:
      - "8081:8081" 
    networks:
      - my-network
    environment:
      - DOTNET_API_PORT=8081
networks:
  my-network:
    driver: bridge