# console-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: console-app
  template:
    metadata:
      labels:
        app: console-app
    spec:
      containers:
      - name: console-container
        image: boneyabraham/deliveggie-consoleapp
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: console-api-service
spec:
  selector:
    app: console-app
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
